/**
 * Author:        Johannes Heidelbach <johannes.heidelbach@gmail.com>
 * Version:       2016/01/30 12:30
 * Description:   This program reads single characters and outputs the
 *                corresponding decimal and hexadecimal value
 * Requirements: 
 *          - Exectution by Bash
 *          - Linux System
 */

#ifndef __linux__
#error "This file works only for Linux"
#endif

#include "../stdLib_c/disable_buffer.h"

#include <stdio.h>
#include <signal.h>
#include <unistd.h>

struct _cursor {
  int line, col;
};

static struct _cursor cursor;

void signalhandler(int signal)
{
  switch(signal)
  {
    case SIGINT:
    case SIGTERM:
      printf("\n\n\n\n");
      fclose(stdin);
      break;
  }
}

static void register_signalhandler()
{
  struct sigaction sigaction_new;
  sigemptyset(&(sigaction_new.sa_mask));
  sigaction_new.sa_flags = SA_RESETHAND;
  sigaction_new.sa_handler = signalhandler;
  sigaction(SIGINT, &sigaction_new, NULL);
}

static void set_cursor()
{
  printf("\033[%d;%dH", cursor.line, cursor.col);
}

/**
 * clears the screen and sets cursor to 0,0
 */
static void clear_screen()
{
  printf("\033[2J");
  cursor.line = 0;
  cursor.col = 0;
  set_cursor();
}

static void erase_to_end()
{
  printf("\033[K\r");
}

static void print_prompt()
{
  erase_to_end();
  printf(">CHAR\n");
  printf(" DEC:\n");
  printf(" HEX:");
  cursor.col = 7;
  set_cursor();
}

static void enter_new_line()
{
  printf("\n\n\n\n");
  cursor.line += 4;
  cursor.col = 0;
  set_cursor();
}

static void print_entry(char c)
{
  set_cursor();
  if ( c == 0 || c < 0 )
    printf("%s", "??");
  else if (c == '\n')
    printf("NL");
  else
    printf("%c", c);
  ++cursor.line;
  set_cursor();
  if ( c == 0 || c < 0 )
    printf("%s", "???");
  else
    printf("%3d", c);
  ++cursor.line;
  set_cursor();
  if ( c == 0 || c < 0 )
    printf("%s", " ??");
  else
    printf(" %02x", c);
  cursor.line -= 2;
  cursor.col += 4;
  set_cursor();
  if (cursor.col + 4 > 80)
  {
    enter_new_line();
    set_cursor();
    print_prompt();
  }
}

static void delete_entry()
{
  if (cursor.col < 8)
  {
    if (cursor.line == 2) // no input to delete
      return;
    cursor.col = 0;
    for (int i = 0; i < 3; ++i)
    {
      set_cursor();
      erase_to_end();
      ++cursor.line;
    }
    cursor.line -= 7;
    cursor.col = 75;
  }
  else
  {
    cursor.col -= 4;
  }
  set_cursor();
  for (int i = 0; i < 3; ++i)
  {
    printf("%4s", "");
    ++cursor.line;
    set_cursor();
  }
  cursor.line -= 3;
  set_cursor();
}

static void read_char_loop()
{
  register_signalhandler();
  disable_buffering();
  clear_screen();
  printf("Please enter some chars\n");
  cursor.line += 2;
  set_cursor();
  print_prompt();
  while (1)
  {
    int c = getchar();
    if (c < 0)
    {
      break;
    }
    else if (c < 0x20) // control sequences
    {
      if (c == '\n')
        print_entry(c);
      else
        set_cursor();
      continue;
    }
    else if (c > 0x80)
    {
      print_entry(0);
    }
    else if (c == 0x7f) // backspace
    {
      // delete output generated by entering backspace
      set_cursor();
      printf("  \b\b");
      
      // delete last entry
      delete_entry();
      continue;
    }
    print_entry(c);
  }
}

int main()
{
  read_char_loop();
  enter_new_line();
  return 0;
}
